import { motion } from 'framer-motion';
import { CheckSquare, Clock, AlertCircle, Check, Loader, Pause, XCircle, Bot } from 'lucide-react';
import { useState } from 'react';

type TaskStatus = 'pending' | 'in_progress' | 'waiting' | 'completed' | 'failed';

interface Task {
  id: number;
  name: string;
  description: string;
  status: TaskStatus;
  priority: 'alta' | 'media' | 'baja';
  date: string;
  agent?: string;
  progress?: number;
  autoGenerated?: boolean;
}

const mockTasks: Task[] = [
  { id: 1, name: 'Deploy API v2.3', description: 'Desplegar nueva versión del API en producción', status: 'in_progress', priority: 'alta', date: 'Hoy', agent: 'Coding Agent', progress: 67, autoGenerated: true },
  { id: 2, name: 'Revisar pull requests', description: '3 PRs pendientes de revisión en el repositorio principal', status: 'pending', priority: 'media', date: 'Hoy' },
  { id: 3, name: 'Backup base de datos', description: 'Esperando ventana de mantenimiento', status: 'waiting', priority: 'alta', date: 'Hoy', progress: 30 },
  { id: 4, name: 'Organizar carpeta Descargas', description: 'Clasificar archivos por tipo y fecha', status: 'completed', priority: 'baja', date: 'Ayer', autoGenerated: true },
  { id: 5, name: 'Actualizar dependencias', description: 'npm audit found 2 vulnerabilities', status: 'failed', priority: 'media', date: 'Ayer' },
  { id: 6, name: 'Generar reporte semanal', description: 'Resumen de actividad y métricas', status: 'pending', priority: 'media', date: 'Mañana', autoGenerated: true },
];

const statusConfig: Record<TaskStatus, { icon: typeof Clock; color: string; label: string }> = {
  pending: { icon: Clock, color: 'var(--text-secondary)', label: 'Pendiente' },
  in_progress: { icon: Loader, color: 'var(--accent)', label: 'En progreso' },
  waiting: { icon: Pause, color: 'var(--warning)', label: 'Esperando' },
  completed: { icon: Check, color: 'var(--success)', label: 'Completada' },
  failed: { icon: XCircle, color: 'var(--danger)', label: 'Fallida' },
};

const priorityColors: Record<string, string> = {
  alta: 'var(--danger)',
  media: 'var(--warning)',
  baja: 'var(--text-tertiary)',
};

const filters = ['Todas', 'Pendientes', 'En progreso', 'Completadas', 'Fallidas'];

export default function TasksView() {
  const [activeFilter, setActiveFilter] = useState('Todas');

  const filtered = mockTasks.filter(t => {
    if (activeFilter === 'Pendientes') return t.status === 'pending';
    if (activeFilter === 'En progreso') return t.status === 'in_progress' || t.status === 'waiting';
    if (activeFilter === 'Completadas') return t.status === 'completed';
    if (activeFilter === 'Fallidas') return t.status === 'failed';
    return true;
  });

  return (
    <div className="h-full flex flex-col p-6 overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'var(--accent-soft)' }}>
          <CheckSquare size={20} style={{ color: 'var(--accent)' }} />
        </div>
        <div>
          <h1 className="text-xl font-semibold" style={{ color: 'var(--text)' }}>Tareas</h1>
          <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
            {mockTasks.filter(t => t.status !== 'completed').length} activas · {mockTasks.filter(t => t.autoGenerated).length} generadas por JARVIS
          </p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex gap-1.5 mb-5">
        {filters.map((f) => (
          <button
            key={f}
            onClick={() => setActiveFilter(f)}
            className="px-3 py-1.5 rounded-full text-xs transition-all"
            style={{
              background: activeFilter === f ? 'var(--accent-soft)' : 'var(--surface)',
              color: activeFilter === f ? 'var(--accent)' : 'var(--text-secondary)',
              border: `1px solid ${activeFilter === f ? 'var(--accent)' : 'var(--border-subtle)'}`,
            }}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Task list */}
      <div className="flex-1 overflow-y-auto space-y-2">
        {filtered.map((task, i) => {
          const config = statusConfig[task.status];
          const Icon = config.icon;
          return (
            <motion.div
              key={task.id}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="group p-4 rounded-xl transition-all hover:scale-[1.01] cursor-pointer"
              style={{ background: 'var(--surface)', border: '1px solid var(--border-subtle)' }}
            >
              <div className="flex items-start gap-3">
                <div className="mt-0.5">
                  <Icon size={16} style={{ color: config.color }} className={task.status === 'in_progress' ? 'animate-spin' : ''} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <p className={`text-sm font-medium ${task.status === 'completed' ? 'line-through opacity-60' : ''}`} style={{ color: 'var(--text)' }}>
                      {task.name}
                    </p>
                    {task.autoGenerated && (
                      <span className="flex items-center gap-1 px-1.5 py-0.5 rounded text-[9px]" style={{ background: 'var(--accent-soft)', color: 'var(--accent)' }}>
                        <Bot size={9} /> JARVIS
                      </span>
                    )}
                  </div>
                  <p className="text-xs mt-1" style={{ color: 'var(--text-tertiary)' }}>{task.description}</p>
                  <div className="flex items-center gap-3 mt-2">
                    <span className="text-[10px] px-2 py-0.5 rounded-full" style={{ color: config.color, background: `${config.color}15` }}>
                      {config.label}
                    </span>
                    <span className="text-[10px]" style={{ color: priorityColors[task.priority] }}>
                      ● {task.priority}
                    </span>
                    <span className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>{task.date}</span>
                    {task.agent && (
                      <span className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>🤖 {task.agent}</span>
                    )}
                  </div>
                  {/* Progress bar */}
                  {task.progress !== undefined && task.status !== 'completed' && (
                    <div className="mt-2 h-1 rounded-full overflow-hidden" style={{ background: 'var(--surface-secondary)' }}>
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${task.progress}%` }}
                        transition={{ duration: 1, delay: i * 0.1 }}
                        className="h-full rounded-full"
                        style={{ background: config.color }}
                      />
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
